spring:
  application:
    name: discovery-service-consumer

server:
  port: 8081

discovery-service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.ocean.discovery.plugin.ribbon.DiscoveryRoundRibbonRule

discovery-service-consumer:
  ribbon:
    NFLoadBalancerRuleClassName: com.ocean.discovery.plugin.ribbon.DiscoveryRoundRibbonRule

discovery:
  metadata:
    group: discovery-group
    version: 1.0
  datasource:
    nacos:
      server-addr: localhost:8848
      data-id: discovery-route-rules
      namespace: discovery-group
      group: discovery-group